name = input("Please enter your full name: ")
age = int(input("Please " + name + " enter your age: "))
location = input("Please " + name + " enter your location: ")
print('\nPersonal Information\n')
print(f'Hello {name}, you are {age} years old and you live in {location}')